spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/spring_weather?useSSL=false&allowMultiQueries=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: ${password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
  redis:
    host: 127.0.0.1
    port: 6379
    password: ${password}
    jedis:
      pool:
        max-wait: 2000ms
        min-idle: 2
  cache:
    type: redis
  mvc:
    static-path-pattern: /weather_img/**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/static/,classpath:/static/,classpath:/public/
mybatis:
  mapper-locations: classpath:com/yee/springbootdemo/mapper/*Mapper.xml
server:
  port: 8181
logging:
  level:
    root: debug
    org:
      springframework:
        boot:
          autoconfigure: debug
  file:
    name: F:\project_log\spring_weather\out.log
    max-size: 10MB
OpenWeatherApi:
  appid: ${appid}
  appsecret: ${appsecret}
BaiduLocation:
  AK: ${AK}
